version: '3.8'

services:
  anahuarket:
    build:
      context: .
      args:
        - DB_HOST=anahuarket-db
        - DB_PORT=5432
        - DB_USER=myuser
        - DB_PASSWORD=ysecretpassword
        - DB_NAME=mydatabase
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=anahuarket-db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=ysecretpassword
      - DB_NAME=mydatabase
    depends_on:
      - anahuarket-db

  anahuarket-db:
    image: postgres:latest
    container_name: anahuarket-db
    environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: ysecretpassword
        POSTGRES_DB: mydatabase

    ports:
      - "5433:5432"